spring.application.name=demo

# 🚀 FIXED: Tell Spring to look at the environment variables passed by AWS
# 1. Change the driver class to the AWS Wrapper
spring.datasource.driver-class-name=software.amazon.jdbc.Driver

# 2. Add "jdbc:aws-wrapper:postgresql:" to the URL string and activate iam
spring.datasource.url=jdbc:aws-wrapper:postgresql://://amazonaws.com

# 3. Strip out any static password properties
spring.datasource.username=postgres


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.lettuce.pool.max-active=50

# Lettuce Driver Connection Pool Adjustments for High Concurrent Load
spring.data.redis.lettuce.pool.max-active=64
spring.data.redis.lettuce.pool.max-idle=16
spring.data.redis.lettuce.pool.min-idle=4
spring.data.redis.lettuce.command-timeout=1500ms

# Force the use of SSL/TLS to match AWS forced In-Transit Encryption
spring.data.redis.ssl.enabled=true

spring.kafka.property-topic=property-events-topic

# Required connection configs for Kafka producer, consumer, and admin
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.bootstrap-servers=pkc-921jm.us-east-2.aws.confluent.cloud:9092
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='{{ CLUSTER_API_KEY }}' password='{{ CLUSTER_API_SECRET }}';
spring.kafka.properties.security.protocol=SASL_SSL

# Best practice for higher availability in Apache Kafka clients prior to 3.0
spring.kafka.properties.session.timeout.ms=45000

client.id=ccloud-springboot-client-c084382d-d56a-4cac-883a-72aeca1cec63
