spring.application.name=demo

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:property_db}
spring.datasource.username=${DB_USERNAME:postgresadmin}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.lettuce.pool.max-active=50

# Lettuce Driver Connection Pool Adjustments for High Concurrent Load
spring.data.redis.lettuce.pool.max-active=64
spring.data.redis.lettuce.pool.max-idle=16
spring.data.redis.lettuce.pool.min-idle=4
spring.data.redis.lettuce.command-timeout=1500ms

# Force the use of SSL/TLS to match AWS forced In-Transit Encryption
spring.data.redis.ssl.enabled=true

spring.kafka.property-topic=properties-lifecycle

# Required connection configs for Kafka producer, consumer, and admin
spring.kafka.properties.sasl.mechanism=PLAIN
spring.kafka.bootstrap-servers=pkc-921jm.us-east-2.aws.confluent.cloud:9092
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username='{{ CLUSTER_API_KEY }}' password='{{ CLUSTER_API_SECRET }}';
spring.kafka.properties.security.protocol=SASL_SSL

# Best practice for higher availability in Apache Kafka clients prior to 3.0
spring.kafka.properties.session.timeout.ms=45000
# Limit the total number of records returned across all partitions in a single poll
spring.kafka.consumer.max-poll-records=20

# Reduce the maximum bytes fetched from any single partition (256 KB instead of 1 MB)
spring.kafka.consumer.properties.max.partition.fetch.bytes=262144

# Cap the absolute maximum data returned for a single fetch request (2 MB instead of 50 MB)
spring.kafka.consumer.properties.fetch.max.bytes=2097152

# Force your custom factory ('kafkaListenerContainerFactory') to throttle its record count
spring.kafka.listener.container-factory.kafkaListenerContainerFactory.consumer.max-poll-records=10

# Force your custom factory to limit bytes per partition
spring.kafka.listener.container-factory.kafkaListenerContainerFactory.consumer.properties.max.partition.fetch.bytes=262144

# Force your custom factory to limit maximum fetch payload size
spring.kafka.listener.container-factory.kafkaListenerContainerFactory.consumer.properties.fetch.max.bytes=1048576

client.id=ccloud-springboot-client-c084382d-d56a-4cac-883a-72aeca1cec63
